### ISSUE TITLE
Inventory Management

### ISSUE THREAD

**Issue by Jimmacle** [Jimmacle/SEWebAPI#1]
Expose inventory information through the API and allow items to be moved around.

Info:
- Allowed item types in inventory
- Current/max volume
- Items in inventory
- (extra) Connected to specified target container ID

Actions:
- Transfer items to and from specific containers
- Pull/push without a specific target container
- Stack certain items in the same container

**Comment by mccorkle** [comment]
I  duplicated some of the issues listed above in my submitted issues.  Would you like me to bring all the details from those issues into here or can we close this as duplicate and work from the individual issues?  @Jimmacle

**Comment by Jimmacle** [comment]
Let's close this and work from individual issues, it'll keep discussion more organized.
